/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DigimonsResponse {
  digimons: [] | [IDigimon];
  pagination: IPagination;
}
export interface IDigimon {
  id: number;
  name: string;
  image: string;
}
export interface IPagination {
  currentPage: number;
  elementsOnPage: number;
  totalElements: number;
  totalPages: number;
  previousPage: string;
  nextPage: number;
}
